name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]   # Trigger when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/myapp || git clone https://github.com/LasinduN/myapp.git ~/myapp
            cd ~/myapp
            git pull origin main
            npm install
            pm2 restart myapp || pm2 start src/index.js --name myapp
